name: relay
description: "A modern, cross-platform API testing client built with Flutter."
publish_to: 'none'
version: 1.0.33+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path: ^1.9.1
  path_provider: ^2.1.5
  file_picker: ^10.3.7
  json_annotation: ^4.9.0
  flutter_riverpod: ^3.0.3
  flutter_widget_from_html_core: ^0.17.0
  shared_preferences: ^2.3.3
  dio: ^5.9.0
  flutter_native_splash: ^2.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  custom_lint: ^0.8.1
  riverpod_lint: ^3.1.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/image/app_logo_rounded.png"
  image_path_ios: "assets/image/app_logo_rounded.png"
  adaptive_icon_foreground: "assets/image/app_logo_rounded.png"
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: "assets/image/app_logo_rounded.png"
  macos:
    generate: true
    image_path: "assets/image/app_logo_rounded.png"

flutter:
  uses-material-design: true
  assets:
    - assets/image/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
